const HASHTAG_REGEX = /^#[A-Za-zА-Яа-яЁё0-9]+$/;
const MAX_HASHTAG_COUNT = 5;
const MAX_HASHTAG_LENGTH = 20;
const MAX_COMMENT_LENGTH = 140;
const DEBOUNCE_DELAY = 500;

export {
  HASHTAG_REGEX,
  MAX_HASHTAG_COUNT,
  MAX_HASHTAG_LENGTH,
  MAX_COMMENT_LENGTH,
  DEBOUNCE_DELAY
};
